apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vx477ao0c-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vx477ao0c-java-springboot-gitops